### PR TITLE
removal of .env file

### PR DESCRIPTION
**Pull request by bmanojlovic**
This PR references .env file removal request #36 and by itself references #24, as now everything is set in docker-compose.yml file, what is not nice is that variables are duplicated but more visible if nothing else

### CODE REVIEW

**Comment by mjhea0** [comment]
Can you resolve the conflicts? Thank you!

**Comment by imaia** [comment]
Is that duplicated code?

**Comment by bmanojlovic** [comment]
I really do not see where is conflict "resolve conflict" raises 404, so if it is possible to tell me what is wrong with my change i would gladly fix it

**Comment by oppianmatt** [comment]
merge the latest master into your branch and it will resolve the conflict

**Comment by bmanojlovic** [comment]
fixed conflict

**Comment by mjhea0** [comment]
thank you! i should have time to look at this later in the week

**Pull request closed without merging**
